######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 22 10:57:12 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . Gui
INCLUDEPATH += . Gui

# Input
HEADERS += Saccade.h SaccadeDetector.h Scan.h ScanParser.h Gui/dialog.h
SOURCES += Scan.cpp \
           ScanParser.cpp \
           ScanParser_test.cpp \
           Gui/dialog.cpp \
           Gui/main.cpp
